
CREATE TABLE Payers
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED NOT NULL,
	[First] NVARCHAR(128) NOT NULL,
	[Last] NVARCHAR(128) NULL,
	CONSTRAINT UQ_Payers_First_Last UNIQUE NONCLUSTERED
	(
		[First], [Last]
	)
);

CREATE TABLE Periods
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED NOT NULL,
	--NOTE: NVARCHAR(450) is the limit to not get warning about uniqueness
	Name NVARCHAR(450) NOT NULL,
	Validated BIT NOT NULL DEFAULT 0,
	CONSTRAINT UQ_Periods_Name UNIQUE NONCLUSTERED
	(
		[Name]
	)
);

-- todo: CREATE TABLE Period_Validation

CREATE TABLE Groups
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED NOT NULL,
	Name NVARCHAR(256) NOT NULL,
	Validated BIT NOT NULL DEFAULT 0,
	PeriodId UNIQUEIDENTIFIER NOT NULL,
	PayerId UNIQUEIDENTIFIER NOT NULL, 
	CONSTRAINT FK_Groups_Periods_PeriodId FOREIGN KEY (PeriodId) REFERENCES Periods(Id),
	CONSTRAINT FK_Groups_Payers_PayerId FOREIGN KEY (PeriodId) REFERENCES Payers(Id),
	CONSTRAINT UQ_Groups_Name_PeriodId UNIQUE NONCLUSTERED
	(
		[Name], [PeriodId]
	)
);

--todo: CREATE TABLE Group_Validation

CREATE TABLE Payments
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED NOT NULL,
	[Type] INT NOT NULL,
	Value decimal(18, 4) NOT NULL,
	GroupId UNIQUEIDENTIFIER NOT NULL,
	PayerId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_Payments_Periods_GroupId FOREIGN KEY (GroupId) REFERENCES Groups(Id),
	CONSTRAINT FK_Payments_Payers_PayerId FOREIGN KEY (PayerId) REFERENCES Payers(Id)
);

--todo: Users