CREATE TABLE Periods
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED,
	--NOTE: NVARCHAR(450) is the limit to not get warning about uniqueness
	Name NVARCHAR(450) NOT NULL UNIQUE,
	Validated BIT NOT NULL DEFAULT 0
);

-- todo: CREATE TABLE Period_Validation

CREATE TABLE Groups
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED,
	Period_Id UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Periods(Id),
	Name NVARCHAR(MAX) NOT NULL,
	Validated BIT NOT NULL DEFAULT 0
);

--todo: CREATE TABLE Group_Validation

CREATE TABLE Payments
(
	Id UNIQUEIDENTIFIER PRIMARY KEY CLUSTERED,
	Group_Id UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Groups(Id),
	Type INT NOT NULL,
	Value decimal(18,4) NOT NULL,
);

--todo: Users